### ISSUE TITLE
MVP: New account creation, login, guest/demo login

### ISSUE THREAD

**Issue by jasonatyu** [jasonatyu/orangemusic#2]
app-link: https://orange-music.herokuapp.com/

# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by eshoule** [comment]
Looking good! You have a couple of items you need to fix before I close this issue (see the uncheck items above). You need more styling on your login/signup forms. Try to make them have more of an apple music aesthetic and just better design in general. I made a couple small changes to point you in the right direction
![Screen Shot 2019-05-02 at 10 36 44 AM](https://user-images.githubusercontent.com/22806373/57094881-66785f80-6cc6-11e9-89e5-4cb915ee1d94.png)

**Comment by jasonatyu** [comment]
I fixed clearing errors and the random route issue. For the the signup/sign in I was trying to replicate the iTunes "Create Apple ID" page - it's pretty basic though any specific examples of what I could fix?

<img width="1267" alt="Screen Shot 2019-04-30 at 10 34 50 AM" src="https://user-images.githubusercontent.com/32180996/57113357-05b64a80-6cf9-11e9-94dc-7995f2dc7778.png">
