### ISSUE TITLE
MVP 2: Playlist CRUD

### ISSUE THREAD

**Issue by jasonatyu** [jasonatyu/orangemusic#3]
Users can see songs and playlists in their library 
Users can create, edit, and delete playlists

**Comment by eshoule** [comment]
Good job! Clean up the styling a bit. Here are some suggestions.
- [ ] Fix photos for playlist index - they are stretched out
- [ ] Your right click popup window needs more styling to look like itunes/apple music
- [ ] Put border radius on your album art for each song in the playlist
- [ ] The separation lines should be shorter so they don't run under the album artwork
- [ ] Do we need the done button on the playlist? When we create a new playlist can it reflect itunes functionality more?
- [ ] Highlight the selected song.

**Comment by jasonatyu** [comment]
Made changes based on feedback but what do you mean by "When we create a new playlist can it reflect itunes functionality more?"

**Comment by jasonatyu** [comment]
Added custom photo upload for playlists
